### ISSUE TITLE
Block breaking delay issue?

### ISSUE THREAD

**Issue by GentlemanCheesy** [Anarchick/skript-packet#36]
Having issues where using this addon with some specific scripts causes a delay in breaking blocks as seen in this video. https://youtu.be/zpoGuKKXKvE

Even this basic test causes it. Disabling all scripts and restarting fixes it. Then enabling one with just this test starts it again.
![image](https://github.com/user-attachments/assets/99389bf3-4d78-478a-ae45-0253e13fdd86)

Using:
Minecraft 1.21.1 - Paper
Skript 2.9.1

**Comment by GentlemanCheesy** [comment]
Changing from "packet event" to "sync packet event" fixed this issue, not sure if that's the intended fix but it doesn't delay block breaking now.

**Comment by Anarchick** [comment]
Yes, it's the fix.
The default event listener use async thread to process some code then switch to the main Thread. This is to ensure low TPS impact but takes more times. This is how ProtocolLib works and that's why I have added the option for full sync / async.

You should use `on sync packet` only when it's really needed.
